event_log1 = [
    {'case_id': 1, 'activity': 'A'},
    {'case_id': 1, 'activity': 'B'},
    {'case_id': 2, 'activity': 'A'},
    {'case_id': 2, 'activity': 'C'},
    {'case_id': 1, 'activity': 'D'},
    {'case_id': 2, 'activity': 'D'},
]

event_log2 = [
    {'case_id': 0, 'activity': 'A'},
    {'case_id': 0, 'activity': 'B'},
    {'case_id': 0, 'activity': 'C'},
    {'case_id': 1, 'activity': 'A'},
    {'case_id': 1, 'activity': 'D'},
    {'case_id': 1, 'activity': 'E'},
    {'case_id': 0, 'activity': 'E'},
    {'case_id': 0, 'activity': 'F'},
    {'case_id': 0, 'activity': 'G'},
    {'case_id': 0, 'activity': 'H'},
    {'case_id': 1, 'activity': 'G'},
    {'case_id': 1, 'activity': 'F'},
    {'case_id': 1, 'activity': 'H'},
    {'case_id': 2, 'activity': 'A'},
    {'case_id': 2, 'activity': 'D'},
    {'case_id': 2, 'activity': 'E'},
    {'case_id': 2, 'activity': 'F'},
    {'case_id': 2, 'activity': 'G'},
    {'case_id': 2, 'activity': 'H'},
    {'case_id': 3, 'activity': 'A'},
    {'case_id': 3, 'activity': 'B'},
    {'case_id': 3, 'activity': 'C'},
    {'case_id': 4, 'activity': 'A'},
    {'case_id': 4, 'activity': 'D'},
    {'case_id': 4, 'activity': 'E'},
    {'case_id': 4, 'activity': 'F'},
    {'case_id': 4, 'activity': 'G'},
    {'case_id': 4, 'activity': 'H'},
    {'case_id': 3, 'activity': 'E'},
    {'case_id': 3, 'activity': 'G'},
    {'case_id': 3, 'activity': 'F'},
    {'case_id': 3, 'activity': 'H'},
    {'case_id': 5, 'activity': 'A'},
    {'case_id': 5, 'activity': 'B'},
    {'case_id': 5, 'activity': 'C'},
    {'case_id': 5, 'activity': 'E'},
    {'case_id': 5, 'activity': 'G'},
    {'case_id': 5, 'activity': 'F'},
    {'case_id': 5, 'activity': 'H'},

]
event_log3 = [
    {"Case id": 0, "Activity": "A"},
    {"Case id": 0, "Activity": "B"},
    {"Case id": 0, "Activity": "D"},
    {"Case id": 1, "Activity": "A"},
    {"Case id": 1, "Activity": "C"},
    {"Case id": 1, "Activity": "G"},
    {"Case id": 1, "Activity": "H"},
    {"Case id": 0, "Activity": "E"},
    {"Case id": 0, "Activity": "F"},
    {"Case id": 0, "Activity": "H"},
    {"Case id": 2, "Activity": "A"},
    {"Case id": 2, "Activity": "C"},
    {"Case id": 2, "Activity": "G"},
    {"Case id": 3, "Activity": "A"},
    {"Case id": 3, "Activity": "C"},
    {"Case id": 2, "Activity": "H"},
    {"Case id": 3, "Activity": "G"},
    {"Case id": 3, "Activity": "H"},
    {"Case id": 4, "Activity": "A"},
    {"Case id": 4, "Activity": "B"},
    {"Case id": 4, "Activity": "E"},
    {"Case id": 4, "Activity": "D"},
    {"Case id": 4, "Activity": "F"},
    {"Case id": 4, "Activity": "H"}
]
event_log4 = [
    {'case_id': 1, 'activity': 'A'},
    {'case_id': 1, 'activity': 'B'},
    {'case_id': 2, 'activity': 'A'},
    {'case_id': 3, 'activity': 'A'},
    {'case_id': 4, 'activity': 'A'},
    {'case_id': 4, 'activity': 'B'},
    {'case_id': 1, 'activity': 'C'},
    {'case_id': 5, 'activity': 'A'},
    {'case_id': 2, 'activity': 'C'},
    {'case_id': 2, 'activity': 'B'},
    {'case_id': 3, 'activity': 'B'},
    {'case_id': 3, 'activity': 'C'},
    {'case_id': 4, 'activity': 'C'},
    {'case_id': 4, 'activity': 'E'},
    {'case_id': 5, 'activity': 'C'},
    {'case_id': 5, 'activity': 'B'},
    {'case_id': 5, 'activity': 'E'},
    {'case_id': 4, 'activity': 'F'},
    {'case_id': 3, 'activity': 'E'},
    {'case_id': 3, 'activity': 'F'},
    {'case_id': 2, 'activity': 'D'},
    {'case_id': 3, 'activity': 'B'},
    {'case_id': 1, 'activity': 'D'},
    {'case_id': 5, 'activity': 'F'},
    {'case_id': 4, 'activity': 'C'},
    {'case_id': 4, 'activity': 'B'},
    {'case_id': 3, 'activity': 'C'},
    {'case_id': 3, 'activity': 'D'},
    {'case_id': 4, 'activity': 'D'},
    {'case_id': 5, 'activity': 'B'},
    {'case_id': 5, 'activity': 'C'},
    {'case_id': 5, 'activity': 'D'},

]